//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action ID.
        /// </summary>
        internal static string ActionIDHeader {
            get {
                return ResourceManager.GetString("ActionIDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action ID Properties.
        /// </summary>
        internal static string ActionIDProperties {
            get {
                return ResourceManager.GetString("ActionIDProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a {0}.
        /// </summary>
        internal static string AddADeviceFormatted {
            get {
                return ResourceManager.GetString("AddADeviceFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device.
        /// </summary>
        internal static string AddDevice {
            get {
                return ResourceManager.GetString("AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add New Clause.
        /// </summary>
        internal static string AddNewClause {
            get {
                return ResourceManager.GetString("AddNewClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rule.
        /// </summary>
        internal static string AddRule {
            get {
                return ResourceManager.GetString("AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string AdministratorRole {
            get {
                return ResourceManager.GetString("AdministratorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm History.
        /// </summary>
        internal static string AlarmHistory {
            get {
                return ResourceManager.GetString("AlarmHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API currently registered for this account.
        /// </summary>
        internal static string ApiRegistrationNotAvailable {
            get {
                return ResourceManager.GetString("ApiRegistrationNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach ICCID to device.
        /// </summary>
        internal static string AttachIccidToDevice {
            get {
                return ResourceManager.GetString("AttachIccidToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Keys.
        /// </summary>
        internal static string AuthenticationKeys {
            get {
                return ResourceManager.GetString("AuthenticationKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Key 1.
        /// </summary>
        internal static string AuthKey1 {
            get {
                return ResourceManager.GetString("AuthKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Key 2.
        /// </summary>
        internal static string AuthKey2 {
            get {
                return ResourceManager.GetString("AuthKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Actions.
        /// </summary>
        internal static string AvailableActions {
            get {
                return ResourceManager.GetString("AvailableActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average of Device Humidity.
        /// </summary>
        internal static string AverageOfDeviceHumidity {
            get {
                return ResourceManager.GetString("AverageOfDeviceHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular Conn.
        /// </summary>
        internal static string CellularConn {
            get {
                return ResourceManager.GetString("CellularConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check ID.
        /// </summary>
        internal static string CheckId {
            get {
                return ResourceManager.GetString("CheckId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to View.
        /// </summary>
        internal static string ClickToDisplayError {
            get {
                return ResourceManager.GetString("ClickToDisplayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select all.
        /// </summary>
        internal static string ClickToSelectAll {
            get {
                return ResourceManager.GetString("ClickToSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command + c to copy.
        /// </summary>
        internal static string CommandCToCopy {
            get {
                return ResourceManager.GetString("CommandCToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery count exceeded..
        /// </summary>
        internal static string CommandDeliveryCountExceeded {
            get {
                return ResourceManager.GetString("CommandDeliveryCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the selected command..
        /// </summary>
        internal static string CommandError {
            get {
                return ResourceManager.GetString("CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string CommandExpired {
            get {
                return ResourceManager.GetString("CommandExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command History.
        /// </summary>
        internal static string CommandHistory {
            get {
                return ResourceManager.GetString("CommandHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Name.
        /// </summary>
        internal static string CommandName {
            get {
                return ResourceManager.GetString("CommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string CommandRejected {
            get {
                return ResourceManager.GetString("CommandRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Results.
        /// </summary>
        internal static string CommandResult {
            get {
                return ResourceManager.GetString("CommandResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the command..
        /// </summary>
        internal static string CommandSendError {
            get {
                return ResourceManager.GetString("CommandSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string CommandSuccess {
            get {
                return ResourceManager.GetString("CommandSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Time Created.
        /// </summary>
        internal static string CommandTimeCreated {
            get {
                return ResourceManager.GetString("CommandTimeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Time Updated.
        /// </summary>
        internal static string CommandTimeUpdated {
            get {
                return ResourceManager.GetString("CommandTimeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values Sent.
        /// </summary>
        internal static string CommandValuesSent {
            get {
                return ResourceManager.GetString("CommandValuesSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control + c to copy.
        /// </summary>
        internal static string ControlCToCopy {
            get {
                return ResourceManager.GetString("ControlCToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy credentials into the configuration file on the device..
        /// </summary>
        internal static string CopyCredentials {
            get {
                return ResourceManager.GetString("CopyCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Field.
        /// </summary>
        internal static string DataFieldHeader {
            get {
                return ResourceManager.GetString("DataFieldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add device. An unexpected error occurred..
        /// </summary>
        internal static string DeviceAddError {
            get {
                return ResourceManager.GetString("DeviceAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device command is disabled..
        /// </summary>
        internal static string DeviceCommandIsDisabled {
            get {
                return ResourceManager.GetString("DeviceCommandIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device commands.
        /// </summary>
        internal static string DeviceCommands {
            get {
                return ResourceManager.GetString("DeviceCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Commands.
        /// </summary>
        internal static string DeviceCommandsHeader {
            get {
                return ResourceManager.GetString("DeviceCommandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Details.
        /// </summary>
        internal static string DeviceDetailsPaneLabel {
            get {
                return ResourceManager.GetString("DeviceDetailsPaneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        internal static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID is available.
        /// </summary>
        internal static string DeviceIdAvailable {
            get {
                return ResourceManager.GetString("DeviceIdAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (DeviceID is case-sensitive).
        /// </summary>
        internal static string DeviceIdCaseSensitiveWarning {
            get {
                return ResourceManager.GetString("DeviceIdCaseSensitiveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID:.
        /// </summary>
        internal static string DeviceIdColon {
            get {
                return ResourceManager.GetString("DeviceIdColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Device ID can only contain letters, numbers, hyphens, and underscores..
        /// </summary>
        internal static string DeviceIdContainsLettersNumbersHyphenUnderscore {
            get {
                return ResourceManager.GetString("DeviceIdContainsLettersNumbersHyphenUnderscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to create the Device ID?.
        /// </summary>
        internal static string DeviceIdCreationPrompt {
            get {
                return ResourceManager.GetString("DeviceIdCreationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        internal static string DeviceIdHeader {
            get {
                return ResourceManager.GetString("DeviceIdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Device ID is already in use..
        /// </summary>
        internal static string DeviceIdInUse {
            get {
                return ResourceManager.GetString("DeviceIdInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID must be between 2 and 128 characters..
        /// </summary>
        internal static string DeviceIDMustBeBetween2And128Characters {
            get {
                return ResourceManager.GetString("DeviceIDMustBeBetween2And128Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Key:.
        /// </summary>
        internal static string DeviceKeyColon {
            get {
                return ResourceManager.GetString("DeviceKeyColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device List.
        /// </summary>
        internal static string DeviceList {
            get {
                return ResourceManager.GetString("DeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not registered in IoT Hub.
        /// </summary>
        internal static string DeviceNotRegisteredInIoTHub {
            get {
                return ResourceManager.GetString("DeviceNotRegisteredInIoTHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Properties.
        /// </summary>
        internal static string DeviceProperties {
            get {
                return ResourceManager.GetString("DeviceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Properties are displayed as stored..
        /// </summary>
        internal static string DevicePropertiesFormattedAsStored {
            get {
                return ResourceManager.GetString("DevicePropertiesFormattedAsStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Rules.
        /// </summary>
        internal static string DeviceRules {
            get {
                return ResourceManager.GetString("DeviceRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All available data fields have rules defined for this device. Please modify an existing rule instead..
        /// </summary>
        internal static string DeviceRulesFullError {
            get {
                return ResourceManager.GetString("DeviceRulesFullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device To View:.
        /// </summary>
        internal static string DeviceToView {
            get {
                return ResourceManager.GetString("DeviceToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update device. An unexpected error occurred..
        /// </summary>
        internal static string DeviceUpdateError {
            get {
                return ResourceManager.GetString("DeviceUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable device.
        /// </summary>
        internal static string DisableDevice {
            get {
                return ResourceManager.GetString("DisableDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Rule.
        /// </summary>
        internal static string DisableRule {
            get {
                return ResourceManager.GetString("DisableRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type: double (like &apos;3.14&apos;, &apos;6.02e+23&apos;, etc).
        /// </summary>
        internal static string DoubleCommandHint {
            get {
                return ResourceManager.GetString("DoubleCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Device Properties.
        /// </summary>
        internal static string EditDeviceProperties {
            get {
                return ResourceManager.GetString("EditDeviceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Device Properties for {0}..
        /// </summary>
        internal static string EditDevicePropertiesForFormatted {
            get {
                return ResourceManager.GetString("EditDevicePropertiesForFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Rule for Device {1}.
        /// </summary>
        internal static string EditDeviceRuleFormatted {
            get {
                return ResourceManager.GetString("EditDeviceRuleFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Device Rule Properties.
        /// </summary>
        internal static string EditDeviceRuleProperties {
            get {
                return ResourceManager.GetString("EditDeviceRuleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable device.
        /// </summary>
        internal static string EnableDevice {
            get {
                return ResourceManager.GetString("EnableDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Rule.
        /// </summary>
        internal static string EnableRule {
            get {
                return ResourceManager.GetString("EnableRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Device ID.
        /// </summary>
        internal static string EnterDeviceId {
            get {
                return ResourceManager.GetString("EnterDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EpiFib.
        /// </summary>
        internal static string EpiFib {
            get {
                return ResourceManager.GetString("EpiFib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove device. An unexpected error occurred..
        /// </summary>
        internal static string ErrorRemoveDevice {
            get {
                return ResourceManager.GetString("ErrorRemoveDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove rule. An unexpected error occurred..
        /// </summary>
        internal static string ErrorRemoveRule {
            get {
                return ResourceManager.GetString("ErrorRemoveRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while retrieving keys.
        /// </summary>
        internal static string ErrorWhileRetrievingKeys {
            get {
                return ResourceManager.GetString("ErrorWhileRetrievingKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve actions..
        /// </summary>
        internal static string FailedToRetrieveActions {
            get {
                return ResourceManager.GetString("FailedToRetrieveActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retreive devices.
        /// </summary>
        internal static string FailedToRetrieveDevices {
            get {
                return ResourceManager.GetString("FailedToRetrieveDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve rules..
        /// </summary>
        internal static string FailedToRetrieveRules {
            get {
                return ResourceManager.GetString("FailedToRetrieveRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update action ID..
        /// </summary>
        internal static string FailedToUpdateActionId {
            get {
                return ResourceManager.GetString("FailedToUpdateActionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update device status.
        /// </summary>
        internal static string FailedToUpdateDeviceStatus {
            get {
                return ResourceManager.GetString("FailedToUpdateDeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Device.
        /// </summary>
        internal static string FalseEnabledDevice {
            get {
                return ResourceManager.GetString("FalseEnabledDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Devices.
        /// </summary>
        internal static string FilterDevices {
            get {
                return ResourceManager.GetString("FilterDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string FilterFieldLabel {
            get {
                return ResourceManager.GetString("FilterFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ total records).
        /// </summary>
        internal static string FilterInfo {
            get {
                return ResourceManager.GetString("FilterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains (case insensitive).
        /// </summary>
        internal static string FilterOperatorContainsInsensitive {
            get {
                return ResourceManager.GetString("FilterOperatorContainsInsensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains (case sensitive).
        /// </summary>
        internal static string FilterOperatorContainsSensitive {
            get {
                return ResourceManager.GetString("FilterOperatorContainsSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact match (case insensitive).
        /// </summary>
        internal static string FilterOperatorExactInsensitive {
            get {
                return ResourceManager.GetString("FilterOperatorExactInsensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact match (case sensitive).
        /// </summary>
        internal static string FilterOperatorExactSensitive {
            get {
                return ResourceManager.GetString("FilterOperatorExactSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string FilterOperatorLabel {
            get {
                return ResourceManager.GetString("FilterOperatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with (case insensitive).
        /// </summary>
        internal static string FilterOperatorStartsWithInsensitive {
            get {
                return ResourceManager.GetString("FilterOperatorStartsWithInsensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with (case sensitive).
        /// </summary>
        internal static string FilterOperatorStartsWithSensitive {
            get {
                return ResourceManager.GetString("FilterOperatorStartsWithSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        internal static string FilterOptionDeviceId {
            get {
                return ResourceManager.GetString("FilterOptionDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Version.
        /// </summary>
        internal static string FilterOptionFirmwareVersion {
            get {
                return ResourceManager.GetString("FilterOptionFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed RAM.
        /// </summary>
        internal static string FilterOptionInstalledRam {
            get {
                return ResourceManager.GetString("FilterOptionInstalledRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string FilterOptionManufacturer {
            get {
                return ResourceManager.GetString("FilterOptionManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number.
        /// </summary>
        internal static string FilterOptionModelNumber {
            get {
                return ResourceManager.GetString("FilterOptionModelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string FilterOptionPlatform {
            get {
                return ResourceManager.GetString("FilterOptionPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        internal static string FilterOptionProcessor {
            get {
                return ResourceManager.GetString("FilterOptionProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string FilterOptionSerialNumber {
            get {
                return ResourceManager.GetString("FilterOptionSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string FilterOptionStatus {
            get {
                return ResourceManager.GetString("FilterOptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string FilterStatusDisabled {
            get {
                return ResourceManager.GetString("FilterStatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string FilterStatusLabel {
            get {
                return ResourceManager.GetString("FilterStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string FilterStatusPending {
            get {
                return ResourceManager.GetString("FilterStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string FilterStatusRunning {
            get {
                return ResourceManager.GetString("FilterStatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string FilterValueLabel {
            get {
                return ResourceManager.GetString("FilterValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Devices.
        /// </summary>
        internal static string FindDevices {
            get {
                return ResourceManager.GetString("FindDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Devices.
        /// </summary>
        internal static string FindDevicesLabelCollapsed {
            get {
                return ResourceManager.GetString("FindDevicesLabelCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string FindLabel {
            get {
                return ResourceManager.GetString("FindLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        internal static string FirmwareHeader {
            get {
                return ResourceManager.GetString("FirmwareHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware version must be less than 200 characters..
        /// </summary>
        internal static string FirmwareVersionMustBeLessThan200Characters {
            get {
                return ResourceManager.GetString("FirmwareVersionMustBeLessThan200Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a Device ID.
        /// </summary>
        internal static string GenerateADeviceId {
            get {
                return ResourceManager.GetString("GenerateADeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implicit Read-Only.
        /// </summary>
        internal static string ImplicitReadOnlyRole {
            get {
                return ResourceManager.GetString("ImplicitReadOnlyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed RAM must be less than 200 characters..
        /// </summary>
        internal static string InstalledRAMFieldMustBeLessThan200Characters {
            get {
                return ResourceManager.GetString("InstalledRAMFieldMustBeLessThan200Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed RAM.
        /// </summary>
        internal static string InstalledRamHeader {
            get {
                return ResourceManager.GetString("InstalledRamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions for your {0}.
        /// </summary>
        internal static string InstructionsForYourDeviceFormatted {
            get {
                return ResourceManager.GetString("InstructionsForYourDeviceFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} has an invalid Telemetry specification on its DeviceInfo.
        /// </summary>
        internal static string InvalidDeviceTelemetryFormat {
            get {
                return ResourceManager.GetString("InvalidDeviceTelemetryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT Hub.
        /// </summary>
        internal static string IoTHub {
            get {
                return ResourceManager.GetString("IoTHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT Hub Name:.
        /// </summary>
        internal static string IoTHubHostName {
            get {
                return ResourceManager.GetString("IoTHubHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a custom Device ID.
        /// </summary>
        internal static string LetMeDefineMyOwnDeviceId {
            get {
                return ResourceManager.GetString("LetMeDefineMyOwnDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Time.
        /// </summary>
        internal static string LocalTime {
            get {
                return ResourceManager.GetString("LocalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string ManufacturerHeader {
            get {
                return ResourceManager.GetString("ManufacturerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max of Device Humidity.
        /// </summary>
        internal static string MaxOfDevicesHumidity {
            get {
                return ResourceManager.GetString("MaxOfDevicesHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min of Device Humidity.
        /// </summary>
        internal static string MinOfDevicesHumidity {
            get {
                return ResourceManager.GetString("MinOfDevicesHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name must be less than 200 characters..
        /// </summary>
        internal static string ModelNameMustBeLessThan200Characters {
            get {
                return ResourceManager.GetString("ModelNameMustBeLessThan200Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number.
        /// </summary>
        internal static string ModelNumberHeader {
            get {
                return ResourceManager.GetString("ModelNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string NavigationMenuItemActions {
            get {
                return ResourceManager.GetString("NavigationMenuItemActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string NavigationMenuItemDashboard {
            get {
                return ResourceManager.GetString("NavigationMenuItemDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string NavigationMenuItemDevices {
            get {
                return ResourceManager.GetString("NavigationMenuItemDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string NavigationMenuItemsAdvanced {
            get {
                return ResourceManager.GetString("NavigationMenuItemsAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Action Selected.
        /// </summary>
        internal static string NoActionSelectedLabel {
            get {
                return ResourceManager.GetString("NoActionSelectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Commands Available.
        /// </summary>
        internal static string NoCommandsAvailable {
            get {
                return ResourceManager.GetString("NoCommandsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Device Selected.
        /// </summary>
        internal static string NoDeviceSelectedLabel {
            get {
                return ResourceManager.GetString("NoDeviceSelectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rule selected..
        /// </summary>
        internal static string NoRuleSelectedLabel {
            get {
                return ResourceManager.GetString("NoRuleSelectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript Required.
        /// </summary>
        internal static string NoscriptHeader {
            get {
                return ResourceManager.GetString("NoscriptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser is currently set to block JavaScript. You need to allow JavaScript to use this service..
        /// </summary>
        internal static string NoscriptP1 {
            get {
                return ResourceManager.GetString("NoscriptP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To learn how to allow JavaScript or to find out whether your browser supports JavaScript, check the online help in your web browser..
        /// </summary>
        internal static string NoscriptP2 {
            get {
                return ResourceManager.GetString("NoscriptP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Devices.
        /// </summary>
        internal static string NumberOfDevicesHeader {
            get {
                return ResourceManager.GetString("NumberOfDevicesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name must be less than 200 characters..
        /// </summary>
        internal static string ObjectNameMustBeLessThan200Characters {
            get {
                return ResourceManager.GetString("ObjectNameMustBeLessThan200Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (opens in new tab).
        /// </summary>
        internal static string OpensInNewTab {
            get {
                return ResourceManager.GetString("OpensInNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string OperatorHeader {
            get {
                return ResourceManager.GetString("OperatorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string PlatformHeader {
            get {
                return ResourceManager.GetString("PlatformHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform name must be less than 200 characters..
        /// </summary>
        internal static string PlatformNameMustBeLessThan200Characters {
            get {
                return ResourceManager.GetString("PlatformNameMustBeLessThan200Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        internal static string ProcessorHeader {
            get {
                return ResourceManager.GetString("ProcessorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor name must be less than 200 characters..
        /// </summary>
        internal static string ProcessorNameMustBeLessThan200Characters {
            get {
                return ResourceManager.GetString("ProcessorNameMustBeLessThan200Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PropertiesPaneLabel {
            get {
                return ResourceManager.GetString("PropertiesPaneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only.
        /// </summary>
        internal static string ReadOnlyRole {
            get {
                return ResourceManager.GetString("ReadOnlyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered but not present.
        /// </summary>
        internal static string RegisteredButNotPresent {
            get {
                return ResourceManager.GetString("RegisteredButNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove device.
        /// </summary>
        internal static string RemoveDevice {
            get {
                return ResourceManager.GetString("RemoveDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Device.
        /// </summary>
        internal static string RemoveDeviceConfirmation {
            get {
                return ResourceManager.GetString("RemoveDeviceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? This will remove this device..
        /// </summary>
        internal static string RemoveDeviceConfirmationPart1 {
            get {
                return ResourceManager.GetString("RemoveDeviceConfirmationPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is permanent..
        /// </summary>
        internal static string RemoveDeviceConfirmationPart2 {
            get {
                return ResourceManager.GetString("RemoveDeviceConfirmationPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove device {0}.
        /// </summary>
        internal static string RemoveDeviceFormatted {
            get {
                return ResourceManager.GetString("RemoveDeviceFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Rule.
        /// </summary>
        internal static string RemoveRule {
            get {
                return ResourceManager.GetString("RemoveRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Rule.
        /// </summary>
        internal static string RemoveRuleButtonLabel {
            get {
                return ResourceManager.GetString("RemoveRuleButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? This will remove this rule from your IoT solution..
        /// </summary>
        internal static string RemoveRuleConfirmationPart1 {
            get {
                return ResourceManager.GetString("RemoveRuleConfirmationPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is permanent..
        /// </summary>
        internal static string RemoveRuleConfirmationPart2 {
            get {
                return ResourceManager.GetString("RemoveRuleConfirmationPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Rule for {0} on Device {1}.
        /// </summary>
        internal static string RemoveRuleFormatted {
            get {
                return ResourceManager.GetString("RemoveRuleFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the {0} parameter is missing or the value was not recognized as a valid {1}.
        /// </summary>
        internal static string RequestFormatError {
            get {
                return ResourceManager.GetString("RequestFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON request data was null or unable to be parsed.  Please ensure the data is sent in the body of the request and correctly formatted..
        /// </summary>
        internal static string RequestNullError {
            get {
                return ResourceManager.GetString("RequestNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        internal static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while resending the command..
        /// </summary>
        internal static string ResendCommandError {
            get {
                return ResourceManager.GetString("ResendCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ResetLabel {
            get {
                return ResourceManager.GetString("ResetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rule for this data field already exists for this device. Only one rule can be defined on a field for a given device. Either try to create a rule for a different data field, or edit the existing rule..
        /// </summary>
        internal static string RuleAlreadyAddedError {
            get {
                return ResourceManager.GetString("RuleAlreadyAddedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule ID.
        /// </summary>
        internal static string RuleIdHeader {
            get {
                return ResourceManager.GetString("RuleIdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Output.
        /// </summary>
        internal static string RuleOutput {
            get {
                return ResourceManager.GetString("RuleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Output.
        /// </summary>
        internal static string RuleOutputHeader {
            get {
                return ResourceManager.GetString("RuleOutputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Properties.
        /// </summary>
        internal static string RuleProperties {
            get {
                return ResourceManager.GetString("RuleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string RulePropertiesPaneLabel {
            get {
                return ResourceManager.GetString("RulePropertiesPaneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Status.
        /// </summary>
        internal static string RuleStatus {
            get {
                return ResourceManager.GetString("RuleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error updating the rule..
        /// </summary>
        internal static string RuleUpdateError {
            get {
                return ResourceManager.GetString("RuleUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and View Rules.
        /// </summary>
        internal static string SaveAndViewRules {
            get {
                return ResourceManager.GetString("SaveAndViewRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save chagnes to device registry..
        /// </summary>
        internal static string SaveChangesToDevice {
            get {
                return ResourceManager.GetString("SaveChangesToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Devices.
        /// </summary>
        internal static string SearchDevices {
            get {
                return ResourceManager.GetString("SearchDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Command.
        /// </summary>
        internal static string SelectACommand {
            get {
                return ResourceManager.GetString("SelectACommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Command.
        /// </summary>
        internal static string SendCommand {
            get {
                return ResourceManager.GetString("SendCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string SerialNumberHeader {
            get {
                return ResourceManager.GetString("SerialNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number must be less than 200 characters..
        /// </summary>
        internal static string SerialNumberMustBeLessThan200Characters {
            get {
                return ResourceManager.GetString("SerialNumberMustBeLessThan200Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service unavailable.
        /// </summary>
        internal static string ServiceUnavailable {
            get {
                return ResourceManager.GetString("ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simulated device has been created with these settings..
        /// </summary>
        internal static string SimulatorCredentialHeader {
            get {
                return ResourceManager.GetString("SimulatorCredentialHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        internal static string StepOneHeader {
            get {
                return ResourceManager.GetString("StepOneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        internal static string StepTwoHeader {
            get {
                return ResourceManager.GetString("StepTwoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a conflict while saving the data. Please verify the data and try again..
        /// </summary>
        internal static string TableDataSaveConflictErrorMessage {
            get {
                return ResourceManager.GetString("TableDataSaveConflictErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00.
        /// </summary>
        internal static string TelemetryGaugeNumericFormat {
            get {
                return ResourceManager.GetString("TelemetryGaugeNumericFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry History.
        /// </summary>
        internal static string TelemetryHistory {
            get {
                return ResourceManager.GetString("TelemetryHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Threshold must be a valid double..
        /// </summary>
        internal static string ThresholdFormatError {
            get {
                return ResourceManager.GetString("ThresholdFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        internal static string ThresholdHeader {
            get {
                return ResourceManager.GetString("ThresholdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Device.
        /// </summary>
        internal static string TrueEnabledDevice {
            get {
                return ResourceManager.GetString("TrueEnabledDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve action from service..
        /// </summary>
        internal static string UnableToRetrieveActionFromService {
            get {
                return ResourceManager.GetString("UnableToRetrieveActionFromService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve alerts history from service..
        /// </summary>
        internal static string UnableToRetrieveAlertsHistoryFromService {
            get {
                return ResourceManager.GetString("UnableToRetrieveAlertsHistoryFromService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retreive device from service..
        /// </summary>
        internal static string UnableToRetrieveDeviceFromService {
            get {
                return ResourceManager.GetString("UnableToRetrieveDeviceFromService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve device telemetry from service..
        /// </summary>
        internal static string UnableToRetrieveDeviceTelemetryFromService {
            get {
                return ResourceManager.GetString("UnableToRetrieveDeviceTelemetryFromService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve rule from service..
        /// </summary>
        internal static string UnableToRetrieveRuleFromService {
            get {
                return ResourceManager.GetString("UnableToRetrieveRuleFromService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command parameter type: &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownCommandParameterType {
            get {
                return ResourceManager.GetString("UnknownCommandParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version must be less than 200 characters..
        /// </summary>
        internal static string VersionMustBeLessThan200Characters {
            get {
                return ResourceManager.GetString("VersionMustBeLessThan200Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View authentication keys.
        /// </summary>
        internal static string ViewAuthenticationKeys {
            get {
                return ResourceManager.GetString("ViewAuthenticationKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Rules.
        /// </summary>
        internal static string ViewRules {
            get {
                return ResourceManager.GetString("ViewRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, remove device {0}.
        /// </summary>
        internal static string YesRemoveDeviceFormatted {
            get {
                return ResourceManager.GetString("YesRemoveDeviceFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, remove the rule for {0} on device {1}.
        /// </summary>
        internal static string YesRemoveRuleFormatted {
            get {
                return ResourceManager.GetString("YesRemoveRuleFormatted", resourceCulture);
            }
        }
    }
}
